### ISSUE TITLE
daemonize profiler for start/stop/restart functionality w/ cockpit

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/wlanpi-profiler#11]
- organize script so that it can be controlled from https://cockpit-project.org/
- perhaps start here: https://stackoverflow.com/questions/16420092/how-to-make-python-script-run-as-service

**Comment by danielmundi** [comment]
@joshschmelzle, you can actually just create a systemd unit service for your script without daemonizing it.
You set ExecStart attribute for the command to execute profiler and systemd will take care of stop and restart.

I can help you with this service if you need.

**Comment by joshschmelzle** [comment]
@danielmundi thanks for the pointer! Let me take a stab at it and I'll pass it by you.

**Comment by joshschmelzle** [comment]
ended up with the following for `profiler.service`:

```
[Unit]
Description=profiler2 service
After=multi-user.target

[Service]
Type=idle
ExecStart=/usr/local/bin/profiler2
```

thanks @danielmundi for the help.
